services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: game_shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - game-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:v4.17.0
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:root@postgres:5432/game_shop?sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - game-network

  game-shop:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: game_shop
      DB_PORT: 5432
    networks:
      - game-network

  notification:
    build: ./notification-service
    ports:
      - "8081:8081"
    networks:
      - game-network

volumes:
  postgres_data:

networks:
  game-network:
    driver: bridge